RealHome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('user.urls', namespace='auth')),
    path('', include('main.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views
from  user import  views as user_vies

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('buy/', views.buy, name='buy'),
    path('sell/', views.sell, name='sell'),
    path('rent/', views.rent, name='rent'),
    path('property/<int:property_id>/', views.details, name='details'),
    path('about/', views.about, name='about'),
    path('terms/', views.terms, name='terms'),
    path('contact-us/', views.contactUs, name='contactUs'),
    path('cookies/', views.cookies, name='cookies'),
    path('privacy-policy/', views.privacyPolicy, name='privacy'),
    path('search/', views.search, name='search'),
    path('property/<int:property_id>/toggle-favorite/', views.toggle_favorite, name='toggle-favorite'),
    path('favorites/', views.favorite_properties, name='favorite-properties'),
    path('realtors/', include('realtors.urls', namespace='realtors')),
    path('property/<int:property_id>/favorite/', views.toggle_favorite, name='toggle_favorite'),
    path('auth/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = "auth"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.logout_view, name='logout'),
]

templates/basics/footer.html
{% load static %}
<footer class="footer">
    <div class="footer-row">
        <div class="footer-row-title"><b>Real Home</b></div>
        <div class="footer-social-icons-row">
            <a href="https://www.instagram.com/?hl=en"><img
                    src="{% static 'Images/Instagram-Icon.png' %}"
                    alt="Instagram" class="footer-social-icons"></a>
            <a href="https://web.facebook.com/?_rdc=1&_rdr"><img
                    src="{% static 'Images/Fackebook-Icon.png' %}"
                    alt="Facebook" class="footer-social-icons"></a>
            <a href="https://www.youtube.com/#!:"><img
                    src="{% static 'Images/Youtube-Icon.png' %}" alt="Youtube"
                    class="footer-social-icons"></a>
            <a href="https://za.pinterest.com/"><img
                    src="{% static 'Images/Pintrest-Icon.png' %}"
                    alt="Pinterest" class="footer-social-icons"></a>
        </div>
    </div>
    <hr color="black">
    <div class="footer-subtext">
        <a href="{% url 'main:about' %}" class="footer-links">About us</a>
        <a href="{% url 'main:contactUs' %}" class="footer-links">Contact us</a>
        <a href="{% url 'main:terms' %}" class="footer-links">Terms &
            Conditions</a>
        <a href="{%url 'main:privacy' %}" class="footer-links">Privacy Policy</a>
        <a href="{% url 'main:cookies' %}" class="footer-links">Cookie Policy</a>
    </div>
    <div class="footer-copyright-lable">
        Copyright © 2024 Real Home
    </div>
    <hr color="black">
</footer>

templates/basics/header.html
{% load static %}

<div class="header">
    <div class="nav">
        <ul class="nav__list">
            <li class="nav__item">
                <a href="{% url 'main:buy' %}" class="nav__link">Buy</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'main:sell' %}" class="nav__link">Sell</a>
            </li>
            <li class="nav__item">
                <a href="{% url 'main:rent' %}" class="nav__link">Rent</a>
            </li>
        </ul>

        <div class="logo-main">
            <a href="{% url 'main:home' %}">
                <img src="{% static 'Images/RealHomeLogo.png' %}" alt="RealHome" class="logo-main__image">
            </a>
        </div>

        <div class="sign-in">
            {% if user.is_authenticated %}
                <a href="{% url 'auth:dashboard' %}" class="sign-in__link">Dashboard</a>
            {% else %}
                <a href="{% url 'auth:register' %}" class="sign-in__link">Sign in</a>
            {% endif %}
        </div>
    </div>
</div>